### ISSUE TITLE
SublimeTextXdebug is not working locally.

### ISSUE THREAD

**Issue by onur-degerli** [martomo/SublimeTextXdebug#63]
Environment data:
- Ubuntu 12.04.4 LTS
- Sublime Text 3, Build 3059
- Installed SublimeTextXdebug with Package Control.
- I am trying to debug locally, through browser.
- Xdebug.sublime-settings
  {
  "path_mapping": {
      "/var/www/xdebug-test" : "/var/www/xdebug-test",
  },
  "url": "http://localhost/xdebug-test/index.php",
  "super_globals": true,
  "close_on_stop": true
  }
- xdebug-test.sublime.project
  {
  "folders":
  [
      {
          "path": "/var/www/xdebug-test"
      }
  ],
  "settings":
  {
      "xdebug": {
          "url": "http://localhost/xdebug-test/index.php",
          "disable_layout": false
      }
  }
  }
- Lastest version of SublimeTextXdebug
- xdebug.ini
  zend_extension=/usr/lib/php5/20121212/xdebug.so
  xdebug.remote_enable = 1
  xdebug.remote_connect_back = 1
  xdebug.remote_port = 9001
- Console output:
  Exception in thread Thread-1375:
  Traceback (most recent call last):
  File "xdebug.protocol in ~/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 182, in listen
  OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "X/threading.py", line 596, in run
  File "main in ~/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 275, in listen
  File "xdebug.protocol in ~/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 188, in listen
Xdebug Client.xdebug.protocol.ProtocolConnectionException: [Errno 98] Address already in use

**Comment by pherris** [comment]
FYI, I was experiencing this issue and the hint about having multiple Sublime windows open was my issue. Once I had just one sublime window open the debugger attached correctly. Thx.

**Comment by wesleymusgrove** [comment]
I am having this issue and closing down multiple Sublime windows did not fix it for me.

See @trungdq88's post: http://stackoverflow.com/questions/35532325/docker-port-conflict-on-ubuntu/35532956 for a detailed explanation on why Sublime cannot listen to port 9000, 9001, or whichever port you are trying to listen for xdebug.

I also receive the following error in Sublime: "Xdebug Client.xdebug.protocol.ProtocolConnectionException: [Errno 98] Address already in use" because the `docker-proxy` process is already listening to port 9000.

**Host:**
* Ubuntu 14.04 LTS
* Sublime Text 3, Build 3059
* Installed SublimeTextXdebug with Package Control.

**SublimeTextXdebug User Settings:**

    {
      "path_mapping": {
      	"/var/www/example/docroot/" : "/srv/example/public_html/example/docroot/"
      },
    	"url": "http://www.example.local/",
    	"port": 9000,
    	"close_on_stop": true,
     	"pretty_output": true,
     	"launch_browser": true,
     	"debug": true
    }


**Guest:**
* Docker container

**20-xdebug.ini:**

    zend_extension = /usr/lib/php5/20121212/xdebug.so
    xdebug.profiler_enable = 1
    xdebug.profiler_output_dir = "/tmp"
    xdebug.default_enable=1
    xdebug.remote_autostart=1
    xdebug.remote_enable=1
    xdebug.remote_handler=dbgp
    xdebug.remote_mode=req
    xdebug.remote_host=172.17.42.1
    xdebug.remote_port=9000
    xdebug.idekey="sublime.xdebug"
    xdebug.remote_connect_back=1
    xdebug.remote_log=/tmp/xdebug.log

**docker-compose.yml:**

    www:
      image: httpd:2.4
      ports: 
        - "80:80"
        - "9000:9000"
      environment:
        XDEBUG_CONFIG: "remote_host=172.17.42.1 remote_port=9000 idekey=sublime.xdebug"
      volumes:
        - public_html:/var/www

**Dockerfile:**

    FROM httpd:2.4
    MAINTAINER Jesus Macias Portela <jmacias@solidgear.es>
    
    # Install xdebug
    RUN apt-get purge \
     && apt-get update \
     && apt-get install -y php5-xdebug
    
    # Add Xdebug configuration
    ADD 20-xdebug.ini /etc/php5/apache2/conf.d/20-xdebug.ini
    
    # Enable php5 mcrypt extension
    RUN php5enmod mcrypt
    
    EXPOSE 80
    EXPOSE 9000

**Output of `tmp/xdebug.log`:**
It immediately closes as soon as it connects to the client

    Log opened at 2016-05-20 14:19:10
    I: Checking remote connect back address.
    I: Remote address found, connecting to 10.12.0.1:9000.
    I: Connected to client. :-)
    -> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///var/www/example/docroot/index.php" language="PHP" protocol_version="1.0" appid="10" idekey="sublime.xdebug"><engine version="2.2.3"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2013 by Derick Rethans]]></copyright></init>
    
    -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="stopping" reason="ok"></response>
    
    Log closed at 2016-05-20 14:19:12

**Output of Sublime Text console:**

    Traceback (most recent call last):
      File "./threading.py", line 901, in _bootstrap_inner
      File "./threading.py", line 858, in run
      File "main in /home/example/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 275, in listen
      File "xdebug.protocol in /home/example/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 250, in listen
    Xdebug Client.xdebug.protocol.ProtocolConnectionException: [Errno 98] Address already in use

As shown in the above mentioned StackOverflow issue, changing the HOST:CONTAINER port mapping to something like `12345:9000` doesn't work because on the HOST the `docker-proxy` process listens to port 12345 and Sublime still cannot listen to port 12345 because it's already in use.

Is there some way for Sublime to listen to port 9000 even if another process is also listening on that port?

As far as I can see, this is like an infinite circle of doom, where Sublime will never be able to listen to xdebug requests coming from a docker container because of the `docker-proxy` service running on the same port that Sublime needs to be listening to on the host.
